springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
