auth:
  jwt:
    secret: ${JWT_SECRET:change-this-in-prod}
    issuer: drawing-app
    access-token-exp-seconds: 3600
    refresh-token-exp-seconds: 1209600
  cors:
    enabled: true
    allowed-origins:
      - "http://localhost:3000"
    allowed-methods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS" ]
    allowed-headers: [ "*" ]
    allow-credentials: true
