server:
  port: 8080
  shutdown: graceful

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    com.example.drawing: INFO
    org.mybatis: INFO
