# DB: 로컬 MySQL을 기본으로 사용 (개발 편의)
db:
  url: ${DB_URL:jdbc:mysql://localhost:3306/drawingdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:password}

# 로그 레벨 상향(원하면)
logging:
  level:
    com.example.drawing: DEBUG
    org.mybatis: DEBUG

# Swagger: dev는 활성화 유지
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# CORS: dev는 느슨하게
auth:
  cors:
    enabled: true
    allowed-origins:
      - "http://localhost:3000"
