server:
  port: ${SERVER_PORT:8080}

db:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  pool:
    max: ${DB_POOL_MAX:30}
    min: ${DB_POOL_MIN:5}
    timeout-ms: ${DB_POOL_TIMEOUT_MS:30000}

spring:
  main:
    banner-mode: "off"

logging:
  level:
    root: INFO
    com.example.drawing: INFO
    org.mybatis: WARN

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

auth:
  cors:
    enabled: ${CORS_ENABLED:false}
    # 쉼표(,)로 여러 도메인 가능: "https://a.com,https://b.com"
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    allowed-methods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS" ]
    allowed-headers: [ "*" ]
    allow-credentials: true
  jwt:
    secret: ${JWT_SECRET}     # 운영은 기본값 없이 강제
    issuer: drawing-app
    access-token-exp-seconds: ${JWT_ACCESS_EXP:3600}
    refresh-token-exp-seconds: ${JWT_REFRESH_EXP:1209600}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
