services:
  mysql:
    image: mysql:8.0
    container_name: drawing-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drawingdb
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: drawing-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/drawingdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: your_prod_secret
      SWAGGER_ENABLED: "true"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50"
    env_file:
      - ../.env
    restart: always

volumes:
  mysql_data:
